-- backfill-posts-count.sql
-- Backfills leads.posts_count from the original Apify scrape CSV.
-- Existing leads in tesserix_admin were imported before migration
-- 0011 added the posts_count column, so every row's posts_count is
-- NULL. This script joins on instagram_handle to populate it.
--
-- Idempotent: IS DISTINCT FROM guards against re-flipping rows that
-- already match. Atomic: single UPDATE in a transaction.
--
-- Source: ~/Downloads/insta-scrape/sellers_no_website.csv
-- Handles: 208  ·  Skipped (missing posts): 0
--
-- Run against prod tesserix-postgres:
--   kubectl -n tesserix run posts-backfill-$(date +%s) --rm -i --restart=Never \
--     --image=postgres:16-alpine \
--     --labels="app.kubernetes.io/component=database-init,app.kubernetes.io/part-of=tesserix" \
--     --overrides='{"metadata":{"annotations":{"sidecar.istio.io/inject":"false"}}}' \
--     --env "PGPASSWORD=$DB_PASS" --env "PGSSLMODE=require" \
--     --command -- psql -h tesserix-postgres-rw.tesserix.svc.cluster.local \
--     -U tesserix_admin -d tesserix_admin -v ON_ERROR_STOP=on \
--     < docs/marketing/seeds/backfill-posts-count.sql

\set ON_ERROR_STOP on

BEGIN;

WITH src(handle, posts) AS (VALUES
  ('olieveandolie'::text, 2970::int),
  ('kissmyhideaustralia'::text, 7558::int),
  ('themysticalhippieau'::text, 676::int),
  ('advital'::text, 504::int),
  ('thread.and.sparkle'::text, 326::int),
  ('designsby_ky'::text, 1308::int),
  ('bpcustomsaus'::text, 308::int),
  ('_foreveretched'::text, 33::int),
  ('__shot__oclock'::text, 48::int),
  ('zatti.au'::text, 6::int),
  ('littlelinesbybec'::text, 95::int),
  ('cloud_wovenbyjp'::text, 32::int),
  ('frecklesanddust'::text, 8::int),
  ('a_little_bit_of_heaven_1'::text, 21::int),
  ('miqiling999'::text, 33::int),
  ('jazzymadebanners'::text, 5::int),
  ('madamebanarsi'::text, 1891::int),
  ('meghamehtadesigns'::text, 633::int),
  ('kamakshi__clothing'::text, 750::int),
  ('white_musk_crafts'::text, 1093::int),
  ('wrappedandready_0'::text, 724::int),
  ('shree_krishna.art'::text, 671::int),
  ('crochet_cart25'::text, 105::int),
  ('foodididi'::text, 36::int),
  ('py_saree_collections'::text, 24043::int),
  ('yards_of_elegance_'::text, 9534::int),
  ('ethnic__bazaar'::text, 951::int),
  ('thepolkadothandmade'::text, 716::int),
  ('crochetartbykalpana'::text, 32::int),
  ('jays_silks_and_sarees'::text, 312::int),
  ('paints_and_strokes'::text, 213::int),
  ('a__k__fashion_jewellery_house'::text, 219::int),
  ('sayyedayub01'::text, 657::int),
  ('krafty.knots'::text, 175::int),
  ('shrinarvya'::text, 8::int),
  ('decor_diva18'::text, 466::int),
  ('snuggleswap'::text, 202::int),
  ('theresinstory_jm'::text, 402::int),
  ('shilpini__'::text, 132::int),
  ('crafteddesk'::text, 460::int),
  ('kavya_homemade_cakes'::text, 585::int),
  ('belove.handmadecrafts'::text, 31::int),
  ('by.sud'::text, 354::int),
  ('shishabyshivani'::text, 1292::int),
  ('nirjalarts'::text, 2::int),
  ('therugpainting'::text, 10::int),
  ('ss_elegant_threads'::text, 1188::int),
  ('magicloops_by_madiha'::text, 21::int),
  ('lively.colours04'::text, 70::int),
  ('tessa.silks_sarees'::text, 1656::int),
  ('royp10683'::text, 706::int),
  ('artistic_pookie_04'::text, 83::int),
  ('aprajita_designs'::text, 179::int),
  ('get_crafty.__'::text, 322::int),
  ('sweetart2329'::text, 419::int),
  ('sparklehook_'::text, 10::int),
  ('_vernaora_'::text, 83::int),
  ('decor_withshree'::text, 134::int),
  ('__chhavi_collection_'::text, 327::int),
  ('the_smol_store'::text, 131::int),
  ('giggleboo_baby'::text, 23::int),
  ('artist_.isha'::text, 156::int),
  ('shweta.digitalmentor'::text, 62::int),
  ('giftitudegallore_byneha'::text, 182::int),
  ('gift_town_11'::text, 243::int),
  ('_.bluuemoon.__'::text, 1579::int),
  ('crochetbyisarwangi'::text, 161::int),
  ('z.a.saree_creation'::text, 96::int),
  ('meetapm'::text, 78::int),
  ('rajgharanafashion.in'::text, 233::int),
  ('houseofphalguni'::text, 30::int),
  ('shreecreations290'::text, 104::int),
  ('kalavan.tribal'::text, 8::int),
  ('mai_toons'::text, 25::int),
  ('sheea.panchal'::text, 497::int),
  ('crochet_by_bhavna_'::text, 66::int),
  ('line_nd_loop'::text, 210::int),
  ('angel_resinart15'::text, 127::int),
  ('tinis_creation'::text, 58::int),
  ('takesandmoments'::text, 100::int),
  ('ar_collection__07'::text, 32::int),
  ('loopspire.handmade'::text, 80::int),
  ('threadtales_saina'::text, 12::int),
  ('luxuryresinbykr'::text, 18::int),
  ('hamparaa.co'::text, 141::int),
  ('thehouseofabhirami'::text, 112::int),
  ('hk_crochet_creations'::text, 12::int),
  ('anabiatrends_kanpur'::text, 65::int),
  ('blissiblecreation'::text, 135::int),
  ('wrappedwth_love'::text, 98::int),
  ('songiri_baawdi'::text, 38::int),
  ('sdcustomgift'::text, 448::int),
  ('alora_hampers_01'::text, 12::int),
  ('royal_rajasthan_prints'::text, 49::int),
  ('kaivarnam156'::text, 24::int),
  ('_cherish_11_'::text, 38::int),
  ('tulja_bhavani_creation_15'::text, 105::int),
  ('essenceandember_jabalpur'::text, 23::int),
  ('sky_export_garments_udt'::text, 52::int),
  ('miss.craftfy'::text, 73::int),
  ('landmark__saree__shop__001'::text, 10::int),
  ('networkofmompreneurs'::text, 16::int),
  ('craft_o_holics_'::text, 80::int),
  ('theprismatelier'::text, 16::int),
  ('resin_artt_world'::text, 2::int),
  ('minique.creations'::text, 39::int),
  ('sonchafaarchitectsnassociates'::text, 3::int),
  ('varnam.closet'::text, 26::int),
  ('highfive.eventss'::text, 21::int),
  ('florabylea'::text, 41::int),
  ('the_soft_drape_co'::text, 30::int),
  ('_.leaper.____'::text, 1317::int),
  ('zivaana.ethnic'::text, 38::int),
  ('gifty_corner'::text, 64::int),
  ('nawabithreadschikankari'::text, 110::int),
  ('tran.quill_.huee'::text, 34::int),
  ('studio_soulloop'::text, 18::int),
  ('pinkbasket02'::text, 3::int),
  ('scentmoir'::text, 23::int),
  ('yaaminiranjith'::text, 15::int),
  ('knot_and_create306'::text, 6::int),
  ('vai_bha_vee'::text, 14::int),
  ('gharki_bunai'::text, 11::int),
  ('threads__andtales'::text, 26::int),
  ('rohinijewellery2026'::text, 12::int),
  ('__golden__gift__'::text, 16::int),
  ('thenail.studio_byds'::text, 3::int),
  ('bhagwati_kala_mandir'::text, 189::int),
  ('the_woven_two_crochet'::text, 33::int),
  ('resina_studio._'::text, 15::int),
  ('vvs_boutique__'::text, 53::int),
  ('khuscurtain5'::text, 7::int),
  ('twirl.and.tie_'::text, 30::int),
  ('__craft_with_creation__'::text, 50::int),
  ('resinostudio'::text, 15::int),
  ('divyas_crochet_magic'::text, 32::int),
  ('theresin_zone'::text, 61::int),
  ('shop.sphere_in'::text, 17::int),
  ('luxe_and_bloom_1925'::text, 5::int),
  ('moms_love_crochet'::text, 6::int),
  ('lilknot_crochet'::text, 3::int),
  ('vrushi.ka.lippan.art'::text, 28::int),
  ('sru.knots'::text, 2::int),
  ('_softlywoven____'::text, 2::int),
  ('the.yarndairies'::text, 19::int),
  ('nara_fashions'::text, 42::int),
  ('giftopiakids'::text, 34::int),
  ('_akanksha_crochetcreation_'::text, 14::int),
  ('whispercrafts_03'::text, 19::int),
  ('resinblooms.in'::text, 4::int),
  ('rainbowexports2020'::text, 316::int),
  ('monaknits.co'::text, 16::int),
  ('amyracreations_offical'::text, 5::int),
  ('itsmannu.fx'::text, 8::int),
  ('poojaresinstudio_11'::text, 74::int),
  ('luearjewels'::text, 9::int),
  ('dacreation_jewellery'::text, 14::int),
  ('mittimuse.claystudio'::text, 23::int),
  ('avarniya_bysimmi'::text, 101::int),
  ('proutlet_khargone'::text, 19::int),
  ('sufnabymann'::text, 20::int),
  ('giftgrambyh'::text, 13::int),
  ('jayaelav_vinoth'::text, 324::int),
  ('neevam.in'::text, 12::int),
  ('giftaholics.india'::text, 58::int),
  ('resinartgallery18'::text, 15::int),
  ('snap_shop.27'::text, 7::int),
  ('littlelady_fashions'::text, 18::int),
  ('marsa.store_1'::text, 14::int),
  ('_._crochetwithluv_._'::text, 1::int),
  ('creates.jd'::text, 11::int),
  ('bridalwalks.luxe'::text, 16::int),
  ('cutiehampers.in'::text, 4::int),
  ('hv_jeweller'::text, 32::int),
  ('aapno_laakh'::text, 23::int),
  ('tidybliss.in'::text, 10::int),
  ('houseofkarigari555'::text, 5::int),
  ('reshamloops.59'::text, 3::int),
  ('nevida.homes'::text, 2::int),
  ('alhaseena.collection'::text, 3::int),
  ('craftybbass'::text, 6::int),
  ('yarn_bop'::text, 2::int),
  ('levericeofficial'::text, 69::int),
  ('rashiatelierverde'::text, 3::int),
  ('crochetmania_25'::text, 20::int),
  ('resin_art_by_chahatt'::text, 2::int),
  ('charms_and_chapters'::text, 3::int),
  ('flossee_creations'::text, 28::int),
  ('kktex_fashion'::text, 29::int),
  ('lunelle._accessories'::text, 6::int),
  ('mutharun_sarees2025'::text, 133::int),
  ('bloomby_digo'::text, 2::int),
  ('theajayenterprises'::text, 6::int),
  ('_.klassykrawchet'::text, 1::int),
  ('rakasarees'::text, 5::int),
  ('haq.mart.official'::text, 9::int),
  ('luxeintimamurradenterprisesllp'::text, 2::int),
  ('bigbootyclay.in'::text, 3::int),
  ('castleofcreations2026'::text, 3::int),
  ('ziare2026'::text, 9::int),
  ('hennacollections'::text, 208::int),
  ('croc.het4616'::text, 3::int),
  ('the.kurti.studio'::text, 1::int),
  ('houseofnishaofficial'::text, 1::int),
  ('the_cozycart25'::text, 10::int),
  ('vrx_precision'::text, 3::int),
  ('ecommitra.ai'::text, 7::int),
  ('amchuridarstudio'::text, 1::int)
)
UPDATE leads
   SET posts_count = src.posts,
       updated_at  = NOW()
  FROM src
 WHERE leads.instagram_handle = src.handle
   AND leads.posts_count IS DISTINCT FROM src.posts;

-- Sanity report
DO $$
DECLARE
  total_with_posts int;
  total_leads int;
BEGIN
  SELECT count(*) FILTER (WHERE posts_count IS NOT NULL),
         count(*) INTO total_with_posts, total_leads
    FROM leads;
  RAISE NOTICE 'backfill: % of % leads now have posts_count', total_with_posts, total_leads;
END $$;

COMMIT;
