// Code generated by cmd/gencatalog. DO NOT EDIT.
//
// Regenerate with:
//   cd services/marketplace-api && go run ./internal/billing/pricing/cmd/gencatalog -o internal/billing/pricing/catalog_data.go
//
// These are the amount tables catalog.go turns into PriceDescriptors: the
// fallback the platform console's billing read routes serve from when the
// console catalog is unconfigured or unreachable. Adding or changing an
// amount by hand here is how the two sources drift; change it in the
// console and regenerate.
//
// Types, lookup-key derivation and the query helpers are hand-written and
// live in catalog.go, alongside the completeness this file has to keep.

package pricing

// developedAmounts maps (plan, period) → per-currency Amount.
// Key: lowercase ISO 4217. Baseline currency is always "usd".
var developedAmounts = map[Plan]map[Period]map[string]Amount{
	PlanStarter: {
		PeriodMonthly: {
			"usd": {Currency: "usd", UnitAmountMinor: 1900},
			"cad": {Currency: "cad", UnitAmountMinor: 2500},
			"gbp": {Currency: "gbp", UnitAmountMinor: 1500},
			"eur": {Currency: "eur", UnitAmountMinor: 1700},
			"aud": {Currency: "aud", UnitAmountMinor: 2900, TaxBehavior: "exclusive"},
			"nzd": {Currency: "nzd", UnitAmountMinor: 2900},
			"sgd": {Currency: "sgd", UnitAmountMinor: 2500},
		},
		PeriodAnnual: {
			// Spec §4.1: $182, C$239, £144, €163, A$278+GST, NZ$278, S$239
			"usd": {Currency: "usd", UnitAmountMinor: 18200},
			"cad": {Currency: "cad", UnitAmountMinor: 23900},
			"gbp": {Currency: "gbp", UnitAmountMinor: 14400},
			"eur": {Currency: "eur", UnitAmountMinor: 16300},
			"aud": {Currency: "aud", UnitAmountMinor: 27800, TaxBehavior: "exclusive"},
			"nzd": {Currency: "nzd", UnitAmountMinor: 27800},
			"sgd": {Currency: "sgd", UnitAmountMinor: 23900},
		},
	},
	PlanStudio: {
		PeriodMonthly: {
			"usd": {Currency: "usd", UnitAmountMinor: 4900},
			"cad": {Currency: "cad", UnitAmountMinor: 6500},
			"gbp": {Currency: "gbp", UnitAmountMinor: 3900},
			"eur": {Currency: "eur", UnitAmountMinor: 4500},
			"aud": {Currency: "aud", UnitAmountMinor: 7500, TaxBehavior: "exclusive"},
			"nzd": {Currency: "nzd", UnitAmountMinor: 7500},
			"sgd": {Currency: "sgd", UnitAmountMinor: 6500},
		},
		PeriodAnnual: {
			// Spec §4.1: $470, C$625, £375, €432, A$719+GST, NZ$719, S$623
			"usd": {Currency: "usd", UnitAmountMinor: 47000},
			"cad": {Currency: "cad", UnitAmountMinor: 62500},
			"gbp": {Currency: "gbp", UnitAmountMinor: 37500},
			"eur": {Currency: "eur", UnitAmountMinor: 43200},
			"aud": {Currency: "aud", UnitAmountMinor: 71900, TaxBehavior: "exclusive"},
			"nzd": {Currency: "nzd", UnitAmountMinor: 71900},
			"sgd": {Currency: "sgd", UnitAmountMinor: 62300},
		},
	},
	PlanPro: {
		PeriodMonthly: {
			// Spec §4.1: monthly at +20% premium over annual-equivalent.
			// Annual: $1188/yr → $99/mo eq → monthly = $99 × 1.20 = $118.80 → $119
			// CAD: C$1619/yr → C$134.92/mo eq → ×1.20 = C$161.90 → C$162
			// GBP: £948/yr → £79/mo eq → ×1.20 = £94.80 → £95
			// EUR: €1068/yr → €89/mo eq → ×1.20 = €106.80 → €107
			// AUD: A$1788/yr → A$149/mo eq → ×1.20 = A$178.80 → A$179
			// NZD: NZ$1788/yr → NZ$149/mo eq → ×1.20 = NZ$178.80 → NZ$179
			// SGD: S$1548/yr → S$129/mo eq → ×1.20 = S$154.80 → S$155
			"usd": {Currency: "usd", UnitAmountMinor: 11900},
			"cad": {Currency: "cad", UnitAmountMinor: 16200},
			"gbp": {Currency: "gbp", UnitAmountMinor: 9500},
			"eur": {Currency: "eur", UnitAmountMinor: 10700},
			"aud": {Currency: "aud", UnitAmountMinor: 17900, TaxBehavior: "exclusive"},
			"nzd": {Currency: "nzd", UnitAmountMinor: 17900},
			"sgd": {Currency: "sgd", UnitAmountMinor: 15500},
		},
		PeriodAnnual: {
			// Spec §4.1: $1,188/yr, C$1,619/yr, £948/yr, €1,068/yr, A$1,788/yr, NZ$1,788/yr, S$1,548/yr
			"usd": {Currency: "usd", UnitAmountMinor: 118800},
			"cad": {Currency: "cad", UnitAmountMinor: 161900},
			"gbp": {Currency: "gbp", UnitAmountMinor: 94800},
			"eur": {Currency: "eur", UnitAmountMinor: 106800},
			"aud": {Currency: "aud", UnitAmountMinor: 178800, TaxBehavior: "exclusive"},
			"nzd": {Currency: "nzd", UnitAmountMinor: 178800},
			"sgd": {Currency: "sgd", UnitAmountMinor: 154800},
		},
	},
}

// pppAmounts holds every PPP price entry keyed by (plan, period, currency).
var pppAmounts = map[pppKey]Amount{
	// --- Starter monthly PPP ---
	// Spec §4.1.1: ₹999, RM59, ฿499, ₱749, Rp199,000, ₫329,000
	{PlanStarter, PeriodMonthly, "inr"}: {Currency: "inr", UnitAmountMinor: 99900},    // 999.00 INR
	{PlanStarter, PeriodMonthly, "myr"}: {Currency: "myr", UnitAmountMinor: 5900},     // 59.00 MYR
	{PlanStarter, PeriodMonthly, "thb"}: {Currency: "thb", UnitAmountMinor: 49900},    // 499.00 THB
	{PlanStarter, PeriodMonthly, "php"}: {Currency: "php", UnitAmountMinor: 74900},    // 749.00 PHP
	{PlanStarter, PeriodMonthly, "idr"}: {Currency: "idr", UnitAmountMinor: 19900000}, // 199,000 IDR (stored ×100)
	{PlanStarter, PeriodMonthly, "vnd"}: {Currency: "vnd", UnitAmountMinor: 32900000}, // 329,000 VND (stored ×100)

	// --- Starter annual PPP ---
	// Spec §4.1.1: ₹9,599, RM569, ฿4,799, ₱7,199, Rp1,919,000, ₫3,169,000
	{PlanStarter, PeriodAnnual, "inr"}: {Currency: "inr", UnitAmountMinor: 959900},    // 9,599.00 INR
	{PlanStarter, PeriodAnnual, "myr"}: {Currency: "myr", UnitAmountMinor: 56900},     // 569.00 MYR
	{PlanStarter, PeriodAnnual, "thb"}: {Currency: "thb", UnitAmountMinor: 479900},    // 4,799.00 THB
	{PlanStarter, PeriodAnnual, "php"}: {Currency: "php", UnitAmountMinor: 719900},    // 7,199.00 PHP
	{PlanStarter, PeriodAnnual, "idr"}: {Currency: "idr", UnitAmountMinor: 191900000}, // 1,919,000 IDR (stored ×100)
	{PlanStarter, PeriodAnnual, "vnd"}: {Currency: "vnd", UnitAmountMinor: 316900000}, // 3,169,000 VND (stored ×100)

	// --- Studio monthly PPP ---
	// Spec §4.1.1: ₹2,499, RM149, ฿1,199, ₱1,899, Rp499,000, ₫799,000
	{PlanStudio, PeriodMonthly, "inr"}: {Currency: "inr", UnitAmountMinor: 249900},   // 2,499.00 INR
	{PlanStudio, PeriodMonthly, "myr"}: {Currency: "myr", UnitAmountMinor: 14900},    // 149.00 MYR
	{PlanStudio, PeriodMonthly, "thb"}: {Currency: "thb", UnitAmountMinor: 119900},   // 1,199.00 THB
	{PlanStudio, PeriodMonthly, "php"}: {Currency: "php", UnitAmountMinor: 189900},   // 1,899.00 PHP
	{PlanStudio, PeriodMonthly, "idr"}: {Currency: "idr", UnitAmountMinor: 49900000}, // 499,000 IDR (stored ×100)
	{PlanStudio, PeriodMonthly, "vnd"}: {Currency: "vnd", UnitAmountMinor: 79900000}, // 799,000 VND (stored ×100)

	// --- Studio annual PPP ---
	// Spec §4.1.1: ₹23,999, RM1,429, ฿11,519, ₱18,239, Rp4,799,000, ₫7,699,000
	{PlanStudio, PeriodAnnual, "inr"}: {Currency: "inr", UnitAmountMinor: 2399900},   // 23,999.00 INR
	{PlanStudio, PeriodAnnual, "myr"}: {Currency: "myr", UnitAmountMinor: 142900},    // 1,429.00 MYR
	{PlanStudio, PeriodAnnual, "thb"}: {Currency: "thb", UnitAmountMinor: 1151900},   // 11,519.00 THB
	{PlanStudio, PeriodAnnual, "php"}: {Currency: "php", UnitAmountMinor: 1823900},   // 18,239.00 PHP
	{PlanStudio, PeriodAnnual, "idr"}: {Currency: "idr", UnitAmountMinor: 479900000}, // 4,799,000 IDR (stored ×100)
	{PlanStudio, PeriodAnnual, "vnd"}: {Currency: "vnd", UnitAmountMinor: 769900000}, // 7,699,000 VND (stored ×100)

	// --- Pro monthly PPP ---
	// Spec §4.1.1 lists only the annual Pro PPP figure for India (₹65,999/yr, ₹5,499/mo eq).
	// Monthly Pro PPP is available at +20% premium over annual-equivalent:
	//   INR: ₹5,499 × 1.20 = ₹6,598.80 → ₹6,599
	//   MYR: RM3,588/12=299 × 1.20 = RM358.80 → RM359
	//   THB: ฿28,788/12=2399 × 1.20 = ฿2,878.80 → ฿2,879
	//   PHP: ₱45,588/12=3799 × 1.20 = ₱4,558.80 → ₱4,559
	//   IDR: Rp11,988,000/12=999,000 × 1.20 = Rp1,198,800 → Rp1,198,800
	//   VND: ₫19,788,000/12=1,649,000 × 1.20 = ₫1,978,800 → ₫1,978,800
	{PlanPro, PeriodMonthly, "inr"}: {Currency: "inr", UnitAmountMinor: 659900},    // 6,599.00 INR
	{PlanPro, PeriodMonthly, "myr"}: {Currency: "myr", UnitAmountMinor: 35900},     // 359.00 MYR
	{PlanPro, PeriodMonthly, "thb"}: {Currency: "thb", UnitAmountMinor: 287900},    // 2,879.00 THB
	{PlanPro, PeriodMonthly, "php"}: {Currency: "php", UnitAmountMinor: 455900},    // 4,559.00 PHP
	{PlanPro, PeriodMonthly, "idr"}: {Currency: "idr", UnitAmountMinor: 119880000}, // 1,198,800 IDR (stored ×100)
	{PlanPro, PeriodMonthly, "vnd"}: {Currency: "vnd", UnitAmountMinor: 197880000}, // 1,978,800 VND (stored ×100)

	// --- Pro annual PPP ---
	// Spec §4.1.1: ₹65,999/yr, RM3,588/yr, ฿28,788/yr, ₱45,588/yr, Rp11,988,000/yr, ₫19,788,000/yr
	{PlanPro, PeriodAnnual, "inr"}: {Currency: "inr", UnitAmountMinor: 6599900},    // 65,999.00 INR
	{PlanPro, PeriodAnnual, "myr"}: {Currency: "myr", UnitAmountMinor: 358800},     // 3,588.00 MYR
	{PlanPro, PeriodAnnual, "thb"}: {Currency: "thb", UnitAmountMinor: 2878800},    // 28,788.00 THB
	{PlanPro, PeriodAnnual, "php"}: {Currency: "php", UnitAmountMinor: 4558800},    // 45,588.00 PHP
	{PlanPro, PeriodAnnual, "idr"}: {Currency: "idr", UnitAmountMinor: 1198800000}, // 11,988,000 IDR (stored ×100)
	{PlanPro, PeriodAnnual, "vnd"}: {Currency: "vnd", UnitAmountMinor: 1978800000}, // 19,788,000 VND (stored ×100)
}
