package pricing

import (
	"fmt"
	"math"
	"strings"
)

// RegenerateCommand is the exact command that produces
// packages/ui/src/subscription/pricing-data.ts from this package. It is
// quoted in the generated file's header and in genpricing_test.go's failure
// message so a reader never has to guess how to fix a stale file.
const RegenerateCommand = "cd services/marketplace-api && go run ./internal/billing/pricing/cmd/genpricing > ../../packages/ui/src/subscription/pricing-data.ts"

// planOrder is the order the three public plans appear in the TS table.
var planOrder = []Plan{PlanStarter, PlanStudio, PlanPro}

// planHeaderComment is the per-plan doc comment above each plan's `prices`
// block in pricing-data.ts. This is prose, not billing data — it summarizes
// catalog.go amounts for a human reader — so it is preserved verbatim here
// rather than derived.
var planHeaderComment = map[Plan][]string{
	PlanStarter: {
		"// Spec §4.1: $19/mo or $182/yr developed markets; ₹999/mo or ₹9,599/yr India PPP.",
	},
	PlanStudio: {
		"// Spec §4.1: $49/mo or $470/yr developed; ₹2,499/mo or ₹23,999/yr India.",
	},
	PlanPro: {
		"// Spec §3.1: annual $1,188/yr ($99/mo eq), monthly $119 (+20% premium).",
		"// Monthly = round(annual / 12 × 1.20) per spec §4.1 + P2 plan.",
	},
}

// planTSID is the TS `id` field for each plan.
var planTSID = map[Plan]string{
	PlanStarter: "starter",
	PlanStudio:  "studio",
	PlanPro:     "pro",
}

// annualMonthlyEquivalent derives the display per-month figure for an
// annual price: round(annual / 12). Not owned by billing — the catalog
// bills annual and monthly as independent Stripe Prices — but verified
// against every row in the committed table (e.g. 18200/12 -> 1517,
// 238800/12 -> 19900).
func annualMonthlyEquivalent(annualMinor int64) int64 {
	return int64(math.Round(float64(annualMinor) / 12))
}

// row renders one `CODE: { monthly: N, annual: N, annualMonthlyEquivalent: N },`
// line at the given indent, with an optional trailing `// comment`.
func row(indent, code string, monthly, annual int64, comment string) string {
	line := fmt.Sprintf("%s%s: { monthly: %d, annual: %d, annualMonthlyEquivalent: %d },",
		indent, code, monthly, annual, annualMonthlyEquivalent(annual))
	if comment != "" {
		line += " // " + comment
	}
	return line
}

// planRow resolves the (monthly, annual, comment) for one plan/currency
// pair, using the developed-tier catalog, then the PPP-tier catalog (INR
// only), then the AED/JPY USD fallback declared in display_extras.go.
func planRow(plan Plan, currency string) (monthly, annual int64, comment string, err error) {
	if amtM, ok := DevelopedAmount(plan, PeriodMonthly, currency); ok {
		amtA, ok := DevelopedAmount(plan, PeriodAnnual, currency)
		if !ok {
			return 0, 0, "", fmt.Errorf("developed monthly present but annual missing: %s/%s", plan, currency)
		}
		if amtM.TaxBehavior == "exclusive" {
			comment = "GST-exclusive"
		}
		return amtM.UnitAmountMinor, amtA.UnitAmountMinor, comment, nil
	}
	if amtM, ok := PPPAmount(plan, PeriodMonthly, currency); ok {
		amtA, ok := PPPAmount(plan, PeriodAnnual, currency)
		if !ok {
			return 0, 0, "", fmt.Errorf("ppp monthly present but annual missing: %s/%s", plan, currency)
		}
		return amtM.UnitAmountMinor, amtA.UnitAmountMinor, "", nil
	}
	for _, fc := range FallbackCurrencies {
		if fc != currency {
			continue
		}
		usdM, ok := DevelopedAmount(plan, PeriodMonthly, "usd")
		if !ok {
			return 0, 0, "", fmt.Errorf("no usd developed amount to fall back to for %s", plan)
		}
		usdA, _ := DevelopedAmount(plan, PeriodAnnual, "usd")
		return usdM.UnitAmountMinor, usdA.UnitAmountMinor, FallbackComment[plan][currency], nil
	}
	return 0, 0, "", fmt.Errorf("no amount found for plan %s currency %s", plan, currency)
}

// GenerateTS renders the full contents of
// packages/ui/src/subscription/pricing-data.ts from catalog.go's
// developedAmounts/pppAmounts plus display_extras.go's display-only values.
func GenerateTS() (string, error) {
	var b strings.Builder

	b.WriteString("// Code generated by cmd/genpricing. DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Regenerate with:\n")
	b.WriteString("//   " + RegenerateCommand + "\n")
	b.WriteString("\n")

	b.WriteString("/**\n")
	b.WriteString(" * Per-currency headline prices for Mark8ly's three public plans\n")
	b.WriteString(" * (Starter / Studio / Pro) plus the Pro+App add-on. All amounts are\n")
	b.WriteString(" * in minor units (cents / paise / subunits).\n")
	b.WriteString(" *\n")
	b.WriteString(" * The Money primitive consumes this data and formats via Intl.\n")
	b.WriteString(" *\n")
	b.WriteString(" * Prices are NOT authored here, and no longer in catalog.go either.\n")
	b.WriteString(" * The platform console owns the catalog (tesserix-home#328); the Go\n")
	b.WriteString(" * tables in catalog_data.go are regenerated from it with\n")
	b.WriteString(" *   " + RegenerateCatalogCommand + " -source=console\n")
	b.WriteString(" * and this file is then regenerated from those tables with:\n")
	b.WriteString(" *   " + RegenerateCommand + "\n")
	b.WriteString(" *\n")
	b.WriteString(" * The Pro+App add-on is the exception: it has no Stripe Price and\n")
	b.WriteString(" * is not in the catalog at all, so its figures come from the\n")
	b.WriteString(" * hand-maintained constants in display_extras.go.\n")
	b.WriteString(" *\n")
	b.WriteString(" * USD is guaranteed to exist for every plan + add-on. All other\n")
	b.WriteString(" * currencies are optional fallbacks — any missing entry falls back\n")
	b.WriteString(" * to USD at render time.\n")
	b.WriteString(" */\n")
	b.WriteString("\n")

	b.WriteString("import type { Currency } from './country-map'\n")
	b.WriteString("\n")
	b.WriteString("export type PlanId = 'starter' | 'studio' | 'pro'\n")
	b.WriteString("\n")
	b.WriteString("export interface PlanPrice {\n")
	b.WriteString("  /** Monthly billing: charged each month in minor units. */\n")
	b.WriteString("  monthly: number\n")
	b.WriteString("  /** Annual billing: charged once a year in minor units. */\n")
	b.WriteString("  annual: number\n")
	b.WriteString("  /** Annual cost expressed as a per-month equivalent for display. */\n")
	b.WriteString("  annualMonthlyEquivalent: number\n")
	b.WriteString("}\n")
	b.WriteString("\n")
	b.WriteString("export interface SharedPlan {\n")
	b.WriteString("  id: PlanId\n")
	b.WriteString("  prices: Partial<Record<Currency, PlanPrice>>\n")
	b.WriteString("}\n")
	b.WriteString("\n")
	b.WriteString("export interface SharedAddOn {\n")
	b.WriteString("  prices: Partial<Record<Currency, PlanPrice>>\n")
	b.WriteString("}\n")
	b.WriteString("\n")
	b.WriteString("export interface SharedPricingCatalogue {\n")
	b.WriteString("  plans: SharedPlan[]\n")
	b.WriteString("  proApp: SharedAddOn\n")
	b.WriteString("}\n")
	b.WriteString("\n")

	b.WriteString("/**\n")
	b.WriteString(" * Source of truth for headline pricing per spec v2.3 §4.1 and §4.1.1.\n")
	b.WriteString(" * Monthly Pro is +20% premium over annual-equivalent (§3.1 Council finding).\n")
	b.WriteString(" *\n")
	b.WriteString(" * Developed markets (USD, CAD, GBP, EUR, AUD, NZD, SGD): USD parity.\n")
	b.WriteString(" * Emerging markets (INR): PPP-adjusted (~33% discount).\n")
	b.WriteString(" * AU prices are GST-EXCLUSIVE — onboarding/admin surfaces must show\n")
	b.WriteString(" * \"Plus GST\" disclosure for AU (§19.4).\n")
	b.WriteString(" * Pro+App add-on is USD-only globally — no PPP or AUD localization\n")
	b.WriteString(" * (§4.1.2); the catalogue still offers per-currency rows for display,\n")
	b.WriteString(" * but billing always bills in USD for the add-on.\n")
	b.WriteString(" *\n")
	b.WriteString(" * AED and JPY have no rows here: we do not serve the Arab or Japanese\n")
	b.WriteString(" * markets they represent (no tested shipping carrier), and a\n")
	b.WriteString(" * USD-fallback row under an AED/JPY label would display as if it were\n")
	b.WriteString(" * a real, if approximate, local price. A visitor whose currency has no\n")
	b.WriteString(" * row here falls back to USD and is shown that — labelled USD.\n")
	b.WriteString(" */\n")
	b.WriteString("export const SHARED_PRICING_CATALOGUE: SharedPricingCatalogue = {\n")
	b.WriteString("  plans: [\n")

	for _, plan := range planOrder {
		b.WriteString("    {\n")
		b.WriteString(fmt.Sprintf("      id: '%s',\n", planTSID[plan]))
		for _, c := range planHeaderComment[plan] {
			b.WriteString("      " + c + "\n")
		}
		b.WriteString("      prices: {\n")
		for _, currency := range DisplayCurrencyOrder {
			monthly, annual, comment, err := planRow(plan, currency)
			if err != nil {
				return "", err
			}
			b.WriteString(row("        ", strings.ToUpper(currency), monthly, annual, comment))
			b.WriteString("\n")
		}
		b.WriteString("      },\n")
		b.WriteString("    },\n")
	}

	b.WriteString("  ],\n")
	b.WriteString("  // Pro+App add-on: spec §4.1.2 — USD-only billing GLOBALLY ($199/mo + $2,000 setup).\n")
	b.WriteString("  // All currencies below show the same USD amount; the display layer should\n")
	b.WriteString("  // annotate \"billed in USD\" for non-USD viewers. Setup fee ($2,000) is a\n")
	b.WriteString("  // separate one-off charge, not included in this monthly figure.\n")
	b.WriteString("  proApp: {\n")
	b.WriteString("    prices: {\n")
	for _, currency := range DisplayCurrencyOrder {
		b.WriteString(row("      ", strings.ToUpper(currency), ProAppMonthly.UnitAmountMinor, ProAppAnnual.UnitAmountMinor, ""))
		b.WriteString("\n")
	}
	b.WriteString("    },\n")
	b.WriteString("  },\n")
	b.WriteString("}\n")
	b.WriteString("\n")

	b.WriteString("/**\n")
	b.WriteString(" * A plan or add-on price resolved to the currency it is actually\n")
	b.WriteString(" * denominated in. When the requested currency has no row, `currency`\n")
	b.WriteString(" * comes back as `'USD'` even though the caller asked for something\n")
	b.WriteString(" * else — callers MUST render `currency`, never the currency they\n")
	b.WriteString(" * requested, or a USD amount ends up mislabelled with the visitor's\n")
	b.WriteString(" * currency code.\n")
	b.WriteString(" */\n")
	b.WriteString("export interface ResolvedPrice {\n")
	b.WriteString("  price: PlanPrice\n")
	b.WriteString("  currency: Currency\n")
	b.WriteString("}\n")
	b.WriteString("\n")
	b.WriteString("/**\n")
	b.WriteString(" * Returns the price for `plan` in `currency`, or the USD fallback\n")
	b.WriteString(" * when the currency isn't covered in the catalogue, alongside the\n")
	b.WriteString(" * currency it actually resolved to. USD is always present — the\n")
	b.WriteString(" * fallback is safe.\n")
	b.WriteString(" */\n")
	b.WriteString("export function getPlanPrice(plan: SharedPlan, currency: Currency): ResolvedPrice {\n")
	b.WriteString("  const localized = plan.prices[currency]\n")
	b.WriteString("  return localized ? { price: localized, currency } : { price: plan.prices.USD!, currency: 'USD' }\n")
	b.WriteString("}\n")
	b.WriteString("\n")
	b.WriteString("/**\n")
	b.WriteString(" * Returns the Pro+App add-on price in `currency`, or the USD fallback,\n")
	b.WriteString(" * alongside the currency it actually resolved to.\n")
	b.WriteString(" */\n")
	b.WriteString("export function getAddOnPrice(addOn: SharedAddOn, currency: Currency): ResolvedPrice {\n")
	b.WriteString("  const localized = addOn.prices[currency]\n")
	b.WriteString("  return localized ? { price: localized, currency } : { price: addOn.prices.USD!, currency: 'USD' }\n")
	b.WriteString("}\n")

	return b.String(), nil
}
