#!/usr/bin/env bash
#
# Pulls the OAuth secrets from GCP Secret Manager into infra/dev/.env.local
# so docker-compose can inject them into platform-api and auth-bff.
#
# Run via:  make dev-secrets
# Auto-run by `make dev`.
#
# Requires: gcloud authenticated as a user with secretAccessor on tesseracthub-480811.
#
# The generated .env.local is gitignored. Never commit it.

set -euo pipefail

PROJECT_ID="tesseracthub-480811"
HERE="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$HERE/../.." && pwd)"
OUT_FILE="$HERE/.env.local"
ONBOARDING_OUT="$REPO_ROOT/apps/onboarding/.env.local"
ADMIN_OUT="$REPO_ROOT/apps/admin/.env.local"

OAUTH_CLIENT_ID="849928263410-5djgu3n40c5tpr86votuptkitqveegor.apps.googleusercontent.com"

if ! command -v gcloud >/dev/null 2>&1; then
  echo "load-secrets: gcloud CLI not found. Install from https://cloud.google.com/sdk" >&2
  exit 1
fi

if ! gcloud auth print-access-token >/dev/null 2>&1; then
  echo "load-secrets: gcloud not authenticated. Run: gcloud auth login" >&2
  exit 1
fi

fetch() {
  local secret_name="$1"
  gcloud secrets versions access latest --secret="$secret_name" --project="$PROJECT_ID" 2>/dev/null
}

echo "load-secrets: fetching from GCP Secret Manager (project=$PROJECT_ID)"

OAUTH_CLIENT_SECRET=$(fetch prod-mp-admin-client-secret)

if [ -z "$OAUTH_CLIENT_SECRET" ]; then
  echo "load-secrets: failed to fetch one or more secrets. Check IAM permissions." >&2
  exit 1
fi

# Generate a deterministic-but-not-prod 32-byte session key for local dev.
# We don't pull the prod cookie key — local sessions should never validate against prod.
SESSION_KEY="dev-only-do-not-use-in-prod-32by"

# GIP was removed on 2026-09-08; its secrets are not fetched here any more.
# Zitadel credentials are NOT pulled either — the Tier-B stack runs without
# an identity provider, and Stage 3 stands up a disposable Zitadel in-stack
# rather than pointing developers at the shared live instance (#858).
cat > "$OUT_FILE" <<EOF
# Generated by infra/dev/load-secrets.sh — DO NOT COMMIT
# Re-generate with: make dev-secrets

OAUTH_CLIENT_ID=$OAUTH_CLIENT_ID
OAUTH_CLIENT_SECRET=$OAUTH_CLIENT_SECRET

SESSION_ENCRYPT_KEY=$SESSION_KEY
EOF

chmod 600 "$OUT_FILE"
echo "load-secrets: wrote $OUT_FILE"

# ─── Mirror the non-GIP values into apps/onboarding/.env.local ────────
# Next.js reads NEXT_PUBLIC_* env vars from the app directory's .env.local.
cat > "$ONBOARDING_OUT" <<EOF
# Generated by infra/dev/load-secrets.sh — DO NOT COMMIT
# Re-generate with: make dev-secrets

# Server-only — used by Next.js server actions / server components.
PLATFORM_API_URL=http://localhost:8086
AUTH_BFF_URL=http://localhost:8087

# Phase M — Google Identity Services popup on /login + onboarding
# "Continue with Google". Same OAuth client used by auth-bff.
NEXT_PUBLIC_GOOGLE_CLIENT_ID=$OAUTH_CLIENT_ID

NEXT_PUBLIC_SITE_URL=http://localhost:4201
EOF

chmod 600 "$ONBOARDING_OUT"
echo "load-secrets: wrote $ONBOARDING_OUT"

# ─── Mirror the same values into apps/admin/.env.local ────────────────
# Admin owns the returning-user /login page (Phase M restructure) and
# needs the Google OAuth credentials directly.
cat > "$ADMIN_OUT" <<EOF
# Generated by infra/dev/load-secrets.sh — DO NOT COMMIT
# Re-generate with: make dev-secrets

# Server-only — used by Next.js server actions / server components.
PLATFORM_API_URL=http://localhost:8086
AUTH_BFF_URL=http://localhost:8087

# Phase M — Google Identity Services popup on admin /login.
NEXT_PUBLIC_GOOGLE_CLIENT_ID=$OAUTH_CLIENT_ID

NEXT_PUBLIC_SITE_URL=http://localhost:4202
NEXT_PUBLIC_MARKETING_URL=http://localhost:4201
EOF

chmod 600 "$ADMIN_OUT"
echo "load-secrets: wrote $ADMIN_OUT"
