// Code generated by cmd/genpricing. DO NOT EDIT.
//
// Regenerate with:
//   cd services/marketplace-api && go run ./internal/billing/pricing/cmd/genpricing > ../../packages/ui/src/subscription/pricing-data.ts

/**
 * Per-currency headline prices for Mark8ly's three public plans
 * (Starter / Studio / Pro) plus the Pro+App add-on. All amounts are
 * in minor units (cents / paise / subunits).
 *
 * The Money primitive consumes this data and formats via Intl.
 *
 * This file is the SINGLE SOURCE OF TRUTH for headline pricing across
 * admin `/pricing` AND onboarding `/#pricing`. To change a price,
 * edit it here and both apps update.
 *
 * USD is guaranteed to exist for every plan + add-on. All other
 * currencies are optional fallbacks — any missing entry falls back
 * to USD at render time.
 */

import type { Currency } from './country-map'

export type PlanId = 'starter' | 'studio' | 'pro'

export interface PlanPrice {
  /** Monthly billing: charged each month in minor units. */
  monthly: number
  /** Annual billing: charged once a year in minor units. */
  annual: number
  /** Annual cost expressed as a per-month equivalent for display. */
  annualMonthlyEquivalent: number
}

export interface SharedPlan {
  id: PlanId
  prices: Partial<Record<Currency, PlanPrice>>
}

export interface SharedAddOn {
  prices: Partial<Record<Currency, PlanPrice>>
}

export interface SharedPricingCatalogue {
  plans: SharedPlan[]
  proApp: SharedAddOn
}

/**
 * Source of truth for headline pricing per spec v2.3 §4.1 and §4.1.1.
 * Monthly Pro is +20% premium over annual-equivalent (§3.1 Council finding).
 *
 * Developed markets (USD, CAD, GBP, EUR, AUD, NZD, SGD): USD parity.
 * Emerging markets (INR): PPP-adjusted (~33% discount).
 * AU prices are GST-EXCLUSIVE — onboarding/admin surfaces must show
 * "Plus GST" disclosure for AU (§19.4).
 * Pro+App add-on is USD-only globally — no PPP or AUD localization
 * (§4.1.2); the catalogue still offers per-currency rows for display,
 * but billing always bills in USD for the add-on.
 *
 * AED and JPY have no rows here: we do not serve the Arab or SEA
 * markets they represent (no tested shipping carrier), and a
 * USD-fallback row under an AED/JPY label would display as if it were
 * a real, if approximate, local price. A visitor whose currency has no
 * row here falls back to USD and is shown that — labelled USD.
 */
export const SHARED_PRICING_CATALOGUE: SharedPricingCatalogue = {
  plans: [
    {
      id: 'starter',
      // Spec §4.1: $19/mo or $182/yr developed markets; ₹999/mo or ₹9,599/yr India PPP.
      prices: {
        USD: { monthly: 1900, annual: 18200, annualMonthlyEquivalent: 1517 },
        CAD: { monthly: 2500, annual: 23900, annualMonthlyEquivalent: 1992 },
        GBP: { monthly: 1500, annual: 14400, annualMonthlyEquivalent: 1200 },
        EUR: { monthly: 1700, annual: 16300, annualMonthlyEquivalent: 1358 },
        AUD: { monthly: 2900, annual: 27800, annualMonthlyEquivalent: 2317 }, // GST-exclusive
        NZD: { monthly: 2900, annual: 27800, annualMonthlyEquivalent: 2317 },
        SGD: { monthly: 2500, annual: 23900, annualMonthlyEquivalent: 1992 },
        INR: { monthly: 99900, annual: 959900, annualMonthlyEquivalent: 79992 },
      },
    },
    {
      id: 'studio',
      // Spec §4.1: $49/mo or $470/yr developed; ₹2,499/mo or ₹23,999/yr India.
      prices: {
        USD: { monthly: 4900, annual: 47000, annualMonthlyEquivalent: 3917 },
        CAD: { monthly: 6500, annual: 62500, annualMonthlyEquivalent: 5208 },
        GBP: { monthly: 3900, annual: 37500, annualMonthlyEquivalent: 3125 },
        EUR: { monthly: 4500, annual: 43200, annualMonthlyEquivalent: 3600 },
        AUD: { monthly: 7500, annual: 71900, annualMonthlyEquivalent: 5992 }, // GST-exclusive
        NZD: { monthly: 7500, annual: 71900, annualMonthlyEquivalent: 5992 },
        SGD: { monthly: 6500, annual: 62300, annualMonthlyEquivalent: 5192 },
        INR: { monthly: 249900, annual: 2399900, annualMonthlyEquivalent: 199992 },
      },
    },
    {
      id: 'pro',
      // Spec §3.1: annual $1,188/yr ($99/mo eq), monthly $119 (+20% premium).
      // Monthly = round(annual / 12 × 1.20) per spec §4.1 + P2 plan.
      prices: {
        USD: { monthly: 11900, annual: 118800, annualMonthlyEquivalent: 9900 },
        CAD: { monthly: 16200, annual: 161900, annualMonthlyEquivalent: 13492 },
        GBP: { monthly: 9500, annual: 94800, annualMonthlyEquivalent: 7900 },
        EUR: { monthly: 10700, annual: 106800, annualMonthlyEquivalent: 8900 },
        AUD: { monthly: 17900, annual: 178800, annualMonthlyEquivalent: 14900 }, // GST-exclusive
        NZD: { monthly: 17900, annual: 178800, annualMonthlyEquivalent: 14900 },
        SGD: { monthly: 15500, annual: 154800, annualMonthlyEquivalent: 12900 },
        INR: { monthly: 659900, annual: 6599900, annualMonthlyEquivalent: 549992 },
      },
    },
  ],
  // Pro+App add-on: spec §4.1.2 — USD-only billing GLOBALLY ($199/mo + $2,000 setup).
  // All currencies below show the same USD amount; the display layer should
  // annotate "billed in USD" for non-USD viewers. Setup fee ($2,000) is a
  // separate one-off charge, not included in this monthly figure.
  proApp: {
    prices: {
      USD: { monthly: 19900, annual: 238800, annualMonthlyEquivalent: 19900 },
      CAD: { monthly: 19900, annual: 238800, annualMonthlyEquivalent: 19900 },
      GBP: { monthly: 19900, annual: 238800, annualMonthlyEquivalent: 19900 },
      EUR: { monthly: 19900, annual: 238800, annualMonthlyEquivalent: 19900 },
      AUD: { monthly: 19900, annual: 238800, annualMonthlyEquivalent: 19900 },
      NZD: { monthly: 19900, annual: 238800, annualMonthlyEquivalent: 19900 },
      SGD: { monthly: 19900, annual: 238800, annualMonthlyEquivalent: 19900 },
      INR: { monthly: 19900, annual: 238800, annualMonthlyEquivalent: 19900 },
    },
  },
}

/**
 * Returns the price for `plan` in `currency`, or the USD fallback
 * when the currency isn't covered in the catalogue. USD is always
 * present — the fallback is safe.
 */
export function getPlanPrice(plan: SharedPlan, currency: Currency): PlanPrice {
  return plan.prices[currency] ?? plan.prices.USD!
}

/**
 * Returns the Pro+App add-on price in `currency`, or the USD fallback.
 */
export function getAddOnPrice(addOn: SharedAddOn, currency: Currency): PlanPrice {
  return addOn.prices[currency] ?? addOn.prices.USD!
}
